// Copyright (c) Sean Lawlor
//
// This source code is licensed under both the MIT license found in the
// LICENSE-MIT file in the root directory of this source tree.

//! Serialization definitions for `ractor_cluster` over-the-network message encoding. This
//! contains helpful types for encoding and decoding messages from raw byte vectors
//!
//! We implement the trait automatically for 8, 16, 32, 64, and 128 bit numerics but we specifically
//! DO NOT implement it for arch-specific types [isize] or [usize] because the may encode at one size
//! on one host and decode at the wrong size at the other host.
//!
//! We additionally provide implementations for [String], [Vec<`char`>], and [Vec<_>] of all numeric values.

/// Trait for use with `ractor_cluster_derive::RactorClusterMessage`
/// derive macro. It defines argument and reply message types which
/// are serializable to/from byte payloads so code can be autogenerated
/// for you by macros for over-the-wire message formats between actors
pub trait BytesConvertable {
    /// Serialize this type to a vector of bytes. Panics are acceptable
    fn into_bytes(self) -> Vec<u8>;
    /// Return the exact serialized length when it can be computed without encoding.
    ///
    /// Generated serializers use this hint to reserve the field prefix and payload in
    /// one allocation. Implementations returning [`Some`] must return the exact number
    /// of bytes appended by [`BytesConvertable::extend_bytes`]. The generated code
    /// validates the hint and returns a serialization error if it does not match.
    #[inline]
    fn serialized_len(&self) -> Option<usize> {
        None
    }
    /// Append this value's serialized representation directly to an existing buffer.
    ///
    /// The default preserves compatibility with existing implementations. Implementors
    /// can override it together with [`BytesConvertable::serialized_len`] to let generated
    /// serializers avoid allocating an intermediate [`Vec`]. When the length is unknown,
    /// generated serializers retain the compatible [`BytesConvertable::into_bytes`] path.
    #[inline]
    fn extend_bytes(self, buffer: &mut Vec<u8>)
    where
        Self: Sized,
    {
        buffer.extend(self.into_bytes());
    }
    /// Deserialize this type from a vector of bytes. Panics are acceptable
    fn from_bytes(bytes: Vec<u8>) -> Self;
    /// Deserialize this type from a borrowed byte slice.
    ///
    /// The default preserves compatibility with existing implementations. Implementors
    /// can override it to avoid copying the input into an intermediate [`Vec`].
    fn from_bytes_ref(bytes: &[u8]) -> Self
    where
        Self: Sized,
    {
        Self::from_bytes(bytes.to_vec())
    }
}

#[cfg(feature = "blanket_serde")]
/// Contains a blanket implementation for all types that implement serde::Serialize and serde::Deserialize
mod impls {
    use crate::BytesConvertable;

    impl<T: serde::Serialize + serde::de::DeserializeOwned> BytesConvertable for T {
        #[inline]
        fn extend_bytes(self, buffer: &mut Vec<u8>) {
            pot::to_writer(&self, buffer).unwrap();
        }
        fn from_bytes(bytes: Vec<u8>) -> Self {
            pot::from_slice(&bytes).unwrap()
        }
        fn from_bytes_ref(bytes: &[u8]) -> Self {
            pot::from_slice(bytes).unwrap()
        }
        fn into_bytes(self) -> Vec<u8> {
            pot::to_vec(&self).unwrap()
        }
    }
}

#[cfg(not(feature = "blanket_serde"))]
/// Contains the default implementations for the `BytesConvertable` trait
mod impls {
    use crate::BytesConvertable;

    // ==================== Primitive implementations ==================== //

    macro_rules! implement_numeric {
        {$ty: ty} => {
            impl BytesConvertable for $ty {
                fn into_bytes(self) -> Vec<u8> {
                    self.to_be_bytes().to_vec()
                }
                #[inline]
                fn serialized_len(&self) -> Option<usize> {
                    Some(std::mem::size_of::<Self>())
                }
                #[inline]
                fn extend_bytes(self, buffer: &mut Vec<u8>) {
                    buffer.extend_from_slice(&self.to_be_bytes());
                }
                fn from_bytes(bytes: Vec<u8>) -> Self {
                    Self::from_bytes_ref(&bytes)
                }
                fn from_bytes_ref(bytes: &[u8]) -> Self {
                    let mut data = [0u8; std::mem::size_of::<Self>()];
                    data.copy_from_slice(&bytes[..std::mem::size_of::<Self>()]);
                    Self::from_be_bytes(data)
                }
            }
        };
    }

    implement_numeric! {i8}
    implement_numeric! {i16}
    implement_numeric! {i32}
    implement_numeric! {i64}
    implement_numeric! {i128}

    implement_numeric! {u8}
    implement_numeric! {u16}
    implement_numeric! {u32}
    implement_numeric! {u64}
    implement_numeric! {u128}

    implement_numeric! {f32}
    implement_numeric! {f64}

    impl BytesConvertable for () {
        fn into_bytes(self) -> Vec<u8> {
            Vec::new()
        }
        #[inline]
        fn serialized_len(&self) -> Option<usize> {
            Some(0)
        }
        #[inline]
        fn extend_bytes(self, _: &mut Vec<u8>) {}
        fn from_bytes(_: Vec<u8>) -> Self {}
        fn from_bytes_ref(_: &[u8]) -> Self {}
    }

    impl BytesConvertable for bool {
        fn into_bytes(self) -> Vec<u8> {
            if self {
                vec![1u8]
            } else {
                vec![0u8]
            }
        }
        #[inline]
        fn serialized_len(&self) -> Option<usize> {
            Some(1)
        }
        #[inline]
        fn extend_bytes(self, buffer: &mut Vec<u8>) {
            buffer.push(u8::from(self));
        }
        fn from_bytes(bytes: Vec<u8>) -> Self {
            Self::from_bytes_ref(&bytes)
        }
        fn from_bytes_ref(bytes: &[u8]) -> Self {
            bytes[0] == 1u8
        }
    }

    impl BytesConvertable for char {
        fn into_bytes(self) -> Vec<u8> {
            let u = self as u32;
            u.into_bytes()
        }
        #[inline]
        fn serialized_len(&self) -> Option<usize> {
            Some(std::mem::size_of::<u32>())
        }
        #[inline]
        fn extend_bytes(self, buffer: &mut Vec<u8>) {
            buffer.extend_from_slice(&(self as u32).to_be_bytes());
        }
        fn from_bytes(bytes: Vec<u8>) -> Self {
            Self::from_bytes_ref(&bytes)
        }
        fn from_bytes_ref(bytes: &[u8]) -> Self {
            let u = u32::from_bytes_ref(bytes);
            Self::from_u32(u).unwrap()
        }
    }

    impl BytesConvertable for String {
        fn into_bytes(self) -> Vec<u8> {
            self.into_bytes()
        }
        #[inline]
        fn serialized_len(&self) -> Option<usize> {
            Some(self.len())
        }
        #[inline]
        fn extend_bytes(self, buffer: &mut Vec<u8>) {
            buffer.extend_from_slice(self.as_bytes());
        }
        fn from_bytes(bytes: Vec<u8>) -> Self {
            String::from_utf8(bytes).unwrap()
        }
        fn from_bytes_ref(bytes: &[u8]) -> Self {
            std::str::from_utf8(bytes).unwrap().to_owned()
        }
    }

    // ==================== Vectorized implementations ==================== //

    macro_rules! implement_vectorized_numeric {
        {$ty: ty} => {
            impl BytesConvertable for Vec<$ty> {
                fn into_bytes(self) -> Vec<u8> {
                    let mut result = vec![0u8; self.len() * std::mem::size_of::<$ty>()];
                    for (offset, item) in self.into_iter().enumerate() {
                        result[offset * std::mem::size_of::<$ty>() .. offset * std::mem::size_of::<$ty>() + std::mem::size_of::<$ty>()].copy_from_slice(&item.to_be_bytes());
                    }
                    result
                }
                #[inline]
                fn serialized_len(&self) -> Option<usize> {
                    self.len().checked_mul(std::mem::size_of::<$ty>())
                }
                #[inline]
                fn extend_bytes(self, buffer: &mut Vec<u8>) {
                    buffer.reserve(self.len() * std::mem::size_of::<$ty>());
                    for item in self {
                        buffer.extend_from_slice(&item.to_be_bytes());
                    }
                }
                fn from_bytes(bytes: Vec<u8>) -> Self {
                    Self::from_bytes_ref(&bytes)
                }
                fn from_bytes_ref(bytes: &[u8]) -> Self {
                    let num_el = bytes.len() / std::mem::size_of::<$ty>();
                    let mut result = vec![<$ty>::MIN; num_el];

                    let mut data = [0u8; std::mem::size_of::<$ty>()];
                    for offset in 0..num_el {
                        data.copy_from_slice(&bytes[offset * std::mem::size_of::<$ty>() .. offset * std::mem::size_of::<$ty>() + std::mem::size_of::<$ty>()]);
                        result[offset] = <$ty>::from_be_bytes(data);
                    }

                    result
                }
            }
        };
    }

    implement_vectorized_numeric! {i8}
    implement_vectorized_numeric! {i16}
    implement_vectorized_numeric! {i32}
    implement_vectorized_numeric! {i64}
    implement_vectorized_numeric! {i128}

    // We explicitly skip u8, as it has a more
    // optimized definition
    impl BytesConvertable for Vec<u8> {
        fn into_bytes(self) -> Vec<u8> {
            self
        }
        #[inline]
        fn serialized_len(&self) -> Option<usize> {
            Some(self.len())
        }
        #[inline]
        fn extend_bytes(self, buffer: &mut Vec<u8>) {
            buffer.extend(self);
        }
        fn from_bytes(bytes: Vec<u8>) -> Self {
            bytes
        }
        fn from_bytes_ref(bytes: &[u8]) -> Self {
            bytes.to_vec()
        }
    }
    implement_vectorized_numeric! {u16}
    implement_vectorized_numeric! {u32}
    implement_vectorized_numeric! {u64}
    implement_vectorized_numeric! {u128}

    implement_vectorized_numeric! {f32}
    implement_vectorized_numeric! {f64}

    impl BytesConvertable for Vec<bool> {
        fn into_bytes(self) -> Vec<u8> {
            let mut result = vec![0u8; self.len()];
            for (ptr, item) in self.into_iter().enumerate() {
                let byte = if item { [1u8] } else { [0u8] };
                result[ptr..ptr + 1].copy_from_slice(&byte);
            }
            result
        }
        #[inline]
        fn serialized_len(&self) -> Option<usize> {
            Some(self.len())
        }
        #[inline]
        fn extend_bytes(self, buffer: &mut Vec<u8>) {
            buffer.reserve(self.len());
            buffer.extend(self.into_iter().map(u8::from));
        }
        fn from_bytes(bytes: Vec<u8>) -> Self {
            Self::from_bytes_ref(&bytes)
        }
        fn from_bytes_ref(bytes: &[u8]) -> Self {
            bytes.iter().map(|byte| *byte == 1u8).collect()
        }
    }

    impl BytesConvertable for Vec<char> {
        fn into_bytes(self) -> Vec<u8> {
            let data = self.into_iter().map(|c| c as u32).collect::<Vec<_>>();
            data.into_bytes()
        }
        #[inline]
        fn serialized_len(&self) -> Option<usize> {
            self.len().checked_mul(std::mem::size_of::<u32>())
        }
        #[inline]
        fn extend_bytes(self, buffer: &mut Vec<u8>) {
            buffer.reserve(self.len() * std::mem::size_of::<u32>());
            for character in self {
                buffer.extend_from_slice(&(character as u32).to_be_bytes());
            }
        }
        fn from_bytes(bytes: Vec<u8>) -> Self {
            Self::from_bytes_ref(&bytes)
        }
        fn from_bytes_ref(bytes: &[u8]) -> Self {
            bytes
                .chunks_exact(std::mem::size_of::<u32>())
                .map(|chunk| {
                    let data: [u8; std::mem::size_of::<u32>()] = chunk.try_into().unwrap();
                    char::from_u32(u32::from_be_bytes(data)).unwrap()
                })
                .collect()
        }
    }
}

#[cfg(test)]
mod tests {
    use rand::distr::Alphanumeric;
    use rand::rng;
    use rand::RngExt;

    use super::BytesConvertable;
    use crate::message::BoxedDowncastErr;
    use crate::Message;

    fn random_string() -> String {
        rng()
            .sample_iter(&Alphanumeric)
            .take(30)
            .map(char::from)
            .collect()
    }

    #[test]
    fn default_buffer_hooks_preserve_legacy_implementations() {
        #[derive(Debug, Eq, PartialEq)]
        struct LegacyBytes(Vec<u8>);

        impl BytesConvertable for LegacyBytes {
            fn into_bytes(self) -> Vec<u8> {
                self.0
            }

            fn from_bytes(bytes: Vec<u8>) -> Self {
                Self(bytes)
            }
        }

        assert_eq!(LegacyBytes(vec![]).serialized_len(), None);
        let mut output = vec![9];
        LegacyBytes(vec![1, 2, 3]).extend_bytes(&mut output);
        assert_eq!(output, vec![9, 1, 2, 3]);
        assert_eq!(
            LegacyBytes::from_bytes_ref(&output[1..]),
            LegacyBytes(vec![1, 2, 3])
        );
    }

    #[cfg(not(feature = "blanket_serde"))]
    #[test]
    fn optimized_buffer_hooks_round_trip_builtin_values() {
        let mut output = vec![9];
        assert_eq!(42u32.serialized_len(), Some(4));
        42u32.extend_bytes(&mut output);
        assert_eq!(u32::from_bytes_ref(&output[1..]), 42);

        output.clear();
        let value = String::from("ractor");
        assert_eq!(value.serialized_len(), Some(6));
        value.extend_bytes(&mut output);
        assert_eq!(String::from_bytes_ref(&output), "ractor");

        output.clear();
        let value = vec![true, false, true];
        assert_eq!(value.serialized_len(), Some(3));
        value.extend_bytes(&mut output);
        assert_eq!(Vec::<bool>::from_bytes_ref(&output), [true, false, true]);

        output.clear();
        let value = vec!['a', 'r'];
        assert_eq!(value.serialized_len(), Some(8));
        value.extend_bytes(&mut output);
        assert_eq!(Vec::<char>::from_bytes_ref(&output), ['a', 'r']);

        output.clear();
        let value = vec![1u8, 2, 3];
        assert_eq!(value.serialized_len(), Some(3));
        value.extend_bytes(&mut output);
        assert_eq!(output, [1, 2, 3]);
    }

    #[cfg(feature = "blanket_serde")]
    #[test]
    fn blanket_serde_uses_the_unknown_length_fallback() {
        let value = String::from("ractor");
        assert_eq!(value.serialized_len(), None);

        let expected = <String as BytesConvertable>::into_bytes(value.clone());
        let mut output = Vec::new();
        value.extend_bytes(&mut output);
        assert_eq!(output, expected);
    }

    macro_rules! run_basic_type_test {
        {$ty: ty} => {
            paste::item! {
                #[test]
                fn [< test_bytes_conversion_ $ty >] () {
                    let test_data: $ty = rand::rng().random();
                    let bytes = test_data.clone().into_bytes();
                    let back = <$ty as BytesConvertable>::from_bytes(bytes);
                    assert_eq!(test_data, back);

                    let serialized_message = test_data.serialize().expect("Failed to serialize type");
                    let deserialized_message = <$ty as Message>::deserialize(serialized_message).expect("Failed to deserialize type");
                    assert_eq!(test_data, deserialized_message);
                }
            }
        };
    }

    macro_rules! run_vector_type_test {
        {$ty: ty} => {
            paste::item! {
                #[test]
                fn [< test_bytes_conversion_vec_ $ty >] () {
                    let mut rng = rand::rng();
                    let num_pts: usize = rng.random_range(10..50);
                    let test_data = (0..num_pts).into_iter().map(|_| rng.random()).collect::<Vec<$ty>>();

                    let bytes = test_data.clone().into_bytes();
                    let back = <Vec<$ty> as BytesConvertable>::from_bytes(bytes);

                    assert_eq!(test_data, back);

                    let serialized_message = test_data.clone().serialize().expect("Failed to serialize type");
                    let deserialized_message = <Vec<$ty> as Message>::deserialize(serialized_message).expect("Failed to deserialize type");
                    assert_eq!(test_data, deserialized_message);
                }
            }
        };
    }

    run_basic_type_test! {i8}
    run_basic_type_test! {i16}
    run_basic_type_test! {i32}
    run_basic_type_test! {i64}
    run_basic_type_test! {i128}
    run_basic_type_test! {u8}
    run_basic_type_test! {u16}
    run_basic_type_test! {u32}
    run_basic_type_test! {u64}
    run_basic_type_test! {u128}
    run_basic_type_test! {f32}
    run_basic_type_test! {f64}
    run_basic_type_test! {char}
    run_basic_type_test! {bool}

    #[test]
    #[allow(non_snake_case)]
    fn test_bytes_conversion_String() {
        let test_data: String = random_string();
        let bytes = <String as BytesConvertable>::into_bytes(test_data.clone());
        let back = <String as BytesConvertable>::from_bytes(bytes);
        assert_eq!(test_data, back);
    }

    run_vector_type_test! {i8}
    run_vector_type_test! {i16}
    run_vector_type_test! {i32}
    run_vector_type_test! {i64}
    run_vector_type_test! {i128}
    run_vector_type_test! {u8}
    run_vector_type_test! {u16}
    run_vector_type_test! {u32}
    run_vector_type_test! {u64}
    run_vector_type_test! {u128}
    run_vector_type_test! {f32}
    run_vector_type_test! {f64}
    run_vector_type_test! {char}
    run_vector_type_test! {bool}

    #[test]
    fn test_boxed_downcast_error() {
        let err = BoxedDowncastErr;
        println!("{err}");
        println!("{err:?}");
    }
}
