name: Unittests for wasm32-unknown-unknown
on:
  push:
    branches: main
  workflow_dispatch: 
  pull_request: 
    types: [opened, reopened, synchronize]

jobs:
  unit-test:
    name: Run unit tests in browser
    runs-on: ubuntu-latest
    strategy:
      matrix:
        enable_async_trait:
          - true
          - false
    steps:
      - uses: actions/checkout@main

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install wasm-pack
        run: cargo install wasm-pack
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Setup test runner
        run: |
          cd ./.github/wasm-test-runner
          npm install
      - name: Run tests (with async-trait)
        if: ${{matrix.enable_async_trait}}
        run: |
          export WORKING_DIR=$(pwd)
          cd ./.github/wasm-test-runner
          node ./index.js async-trait 
      - name: Run tests (without async-trait)
        if: ${{!matrix.enable_async_trait}}
        run: |
          export WORKING_DIR=$(pwd)
          cd ./.github/wasm-test-runner
          node ./index.js
   
